### ISSUE TITLE
Online verify after unistall app

### ISSUE THREAD

**Issue by AhmerAfzal1** [Pritom14/Password-Storage#3]
Hi, 

I appreciate your work, please try to put database in online clouding that can kept previous user credentials. Now it is just store passwords but no having backup facility, please if you can so try to store backup database with signed up username email address and password.

Thanks for great library

**Comment by Pritom14** [comment]
I don't have a lot of experience on online data storage. If you know online
data storage you could send a PR

On 06-Oct-2017 4:50 PM, "Ahmer Afzal" <notifications@github.com> wrote:

Hi,

I appreciate your work, please try to put database in online clouding that
can kept previous user credentials. Now it is just store passwords but no
having backup facility, please if you can so try to store backup database
with signed up username email address and password.

Thanks for great library

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Pritom14/Password-Storage/issues/3>, or mute the thread
