### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#64]
**Summary**
It would be better if there is a gif in place of all the screenshots.Keep the descriptions to the point and remove my name.
The screenshots required for making the gif is present in the screenshots folder.

**Comment by anandwana001** [comment]
@Pritom14 I would like to work on this.

**Comment by anandwana001** [comment]
could you please update the screenshots!

**Comment by Pritom14** [comment]
The screenshots are there in the folder

**Comment by anandwana001** [comment]
@Pritom14  have a look at [this](https://jbt.github.io/markdown-editor/#lVTbTuQ4EH3PVxSNUC/SdgINjZYVDYJhZmAvTHMdzaAVcpLq2IxjZ22nQ/j6LTuE7gXtwz4ltsunTlWd4wNRFmBNNh1w5yr7a5JIvhMXWhcSa4sm08qhcnGmy2TnctTcXpydjvjdZO/rhf3a7n+5/fR8xq7wxH7/c5df/j5azPZPb8bfvt+dX120oiiv7u52ni8n8/Hx0w2bzOS0mWwNgElRqOlA4twNgNuKZTgdbA9g8fp7GEUHDLjB+XTYM6ska1+oBT7WaYMJqyqb5OiYkPZI5FM6iZVwVsiMMxPzKq6YtY02+TXFswKH4Jgp0E2HD6lk6sewp2NEwd3g8MC35F9bwNF/p8OdvWFo1islO96KK20dXYm1KZKyfn7aaXYfedLxfPCcH1KWFxhXqhhCcniQsMNoHWYvpOCFVRQdK6VbzEHPYa49QSdUAa2uDfQVWH8Coqy0cUw5aDC1wqE9ik61j4TG7zKwmNUGadV6NMsWHolJ6VeOYwlCgVYIxC5DWliHLCRujAhZQ1CuGx/m8Tii8+cVq9AcRTcc1bsKQNiOrdWydkKrNTh3EIZkPeBKFYTk2fjNvgRoOBJlXwRnCwRGebNM18r9bPXKdl+bfUlKUG9axFQe4rWSbXfJaTBYYpmi6YJLRhUv74R2mJx2KJLU7n+IGikrjqL7tfuTWkhfJnO1/eunfvbOUF/tKBNh8jPqnC63d5O+LaOXtsR2URylhqmMT7u8m/8bY9Oz+CycZ3aldbkE8MKzXKDMbSx0EpSWFCFy9KiF2hhvkQ0cfTY+jjd+2dvYH49SWQdWKzy6G7Eo36VO/tBp2m5G0Wg0itbX4RRtZkTl5xtdk0egrqARjneNxZJsCCIPQ2DLBjdcZJziaOgpdqGDN0MYxPCJxL1AI+YiYz6BF0GH2N+0SLhOv0kW8jOQQv0IBlnFiOEbaSHzcsrzFZWEOzRlYSBflhR4kxIVLjqtdI6ijCRGtEHHdqnkEPFYW/deZ2+qiyHqWhh1TSx1tHZ/LB3c4JNbzqHEXLC4EBVvwxMX1onc/q2qJ7dX+5c3H+Ynt5/Pky6iEPPNFdQz3XgKH+jJNiKtHZJPyZPCWwK+VGTZa2obGb4y+hEz1xVLFtQ1yZu6y0nxrYewiJD1MNp4c/rS/LMDaV10HpsLiTBHMgXZ0eDfNVpnIW3B1mkputerqmlur2eMgFDKGGYSmcUeUVhL5xD8vyJIXqehB//piqS72HfgHw==) and gif [here](http://gph.is/2yWOawg)

**Comment by anandwana001** [comment]
<img src="https://lh3.googleusercontent.com/3Q-wUNHD-hV56WNsWy9OUFzHaReBsZM4hQK-vP9DT2YZVIRNyigmRVV3zQ5f2AxTa5Pl=w50" align="left" hspace="1" vspace="1">

<a href='https://play.google.com/store/apps/details?id=com.nitsilchar.hp.passwordStorage' target='_blank' align="right"><img align="right" height='36' src='https://s20.postimg.org/muzx3w4jh/google_play_badge.png' /></a>
# Password Storage

Annoyed of forgetting your passwords for important websites?
Do you want a secure way of saving all of them in one place instead of writing them down on a sheet of paper?
Then Password Storage is your solution! It stores the passwords of all the websites where you have an account, so you have a secure storage of your passwords and you only have to remember your master password in order to enter the app.

[![Build Status](https://travis-ci.org/Pritom14/Password-Storage.svg?branch=master)](https://travis-ci.org/Pritom14/Password-Storage) [![Gitter Room](https://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-blue.svg)](https://gitter.im/Password-Storage/Lobby)

---
## Description
Sign up with your email id and a password which will be your "master password". For verification, an email will be sent to your email id with a link for verification. You can add passwords with their description and whenever you want to access these password you just have to remember the master password. 


---


## Demo
![Password-Storage](https://media.giphy.com/media/l1Jpu5UR9QTCfBUGI/giphy.gif)

---


## How to Contribute
This is an Open Source project and we would be happy to see contributors who report bugs and file feature requests by submitting pull requests as well. Please report issues here https://github.com/Pritom14/Password-Storage/issues

---

**Comment by Pritom14** [comment]
@anandwana001 ,please update the mainactivity screenshot and also the details activity. The main activity should contain atleast on list item, and should reflect the recent changes you have made

**Comment by Pritom14** [comment]
Also, upload the screenshots of the recent changes you have made in the main activity in the screenshots folder.

**Comment by anandwana001** [comment]
ok
